"""Estrutura Completa Reset

Revision ID: 0b4b17f22d45
Revises: 
Create Date: 2026-01-31 00:47:34.623401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4b17f22d45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('igreja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cidade_uf', sa.String(length=50), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('cargo_responsavel', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_batismo', sa.Date(), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igreja.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igreja.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['igreja_id'], ['igreja.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=True),
    sa.Column('entidade', sa.String(length=50), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_auditoria')
    op.drop_table('lancamento')
    op.drop_table('usuario')
    op.drop_table('membro')
    op.drop_table('igreja')
    # ### end Alembic commands ###
